# Model arguments
model_name_or_path: deepseek-ai/DeepSeek-R1-Distill-Qwen-14B
output_dir: data/Qwen-14B-GRPO-v0
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2
use_liger_kernel: true
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false

# Data training arguments
# dataset_name: open-r1/OpenR1-Math-220k
dataset_name: hoanganhpham/openr1_hard
dataset_configs:
- train
chat_template: "{% if not add_generation_prompt is defined %}{% set add_generation_prompt = false %}{% endif %}{% set ns = namespace(is_first=false, is_tool=false, is_output_first=true, system_prompt='') %}{%- for message in messages %}{%- if message['role'] == 'system' %}{% set ns.system_prompt = message['content'] %}{%- endif %}{%- endfor %}{{bos_token}}{{ns.system_prompt}}{%- for message in messages %}{%- if message['role'] == 'user' %}{%- set ns.is_tool = false -%}{{'<｜User｜>' + message['content']}}{%- endif %}{%- if message['role'] == 'assistant' and message['content'] is none %}{%- set ns.is_tool = false -%}{%- for tool in message['tool_calls']%}{%- if not ns.is_first %}{{'<｜Assistant｜><｜tool▁calls▁begin｜><｜tool▁call▁begin｜>' + tool['type'] + '<｜tool▁sep｜>' + tool['function']['name'] + '\\n' + '```json' + '\\n' + tool['function']['arguments'] + '\\n' + '```' + '<｜tool▁call▁end｜>'}}{%- set ns.is_first = true -%}{%- else %}{{'\\n' + '<｜tool▁call▁begin｜>' + tool['type'] + '<｜tool▁sep｜>' + tool['function']['name'] + '\\n' + '```json' + '\\n' + tool['function']['arguments'] + '\\n' + '```' + '<｜tool▁call▁end｜>'}}{{'<｜tool▁calls▁end｜><｜end▁of▁sentence｜>'}}{%- endif %}{%- endfor %}{%- endif %}{%- if message['role'] == 'assistant' and message['content'] is not none %}{%- if ns.is_tool %}{{'<｜tool▁outputs▁end｜>' + message['content'] + '<｜end▁of▁sentence｜>'}}{%- set ns.is_tool = false -%}{%- else %}{% set content = message['content'] %}{{'<｜Assistant｜>' + content + '<｜end▁of▁sentence｜>'}}{%- endif %}{%- endif %}{%- if message['role'] == 'tool' %}{%- set ns.is_tool = true -%}{%- if ns.is_output_first %}{{'<｜tool▁outputs▁begin｜><｜tool▁output▁begin｜>' + message['content'] + '<｜tool▁output▁end｜>'}}{%- set ns.is_output_first = false %}{%- else %}{{'\\n<｜tool▁output▁begin｜>' + message['content'] + '<｜tool▁output▁end｜>'}}{%- endif %}{%- endif %}{%- endfor -%}{% if ns.is_tool %}{{'<｜tool▁outputs▁end｜>'}}{% endif %}{% if add_generation_prompt and not ns.is_tool %}{{'<｜Assistant｜>'}}{% endif %}"
system_prompt: "You are a helpful AI Assistant, designed to provided well-reasoned and detailed responses. You FIRST think about the reasoning process as an internal monologue and then provide the user with the answer. The reasoning process MUST BE enclosed within <think> and </think> tags."

# LORA config
use_peft: true
lora_task_type: CAUSAL_LM
lora_r: 64
lora_alpha: 16
lora_dropout: 0.05
lora_target_modules:
- q_proj
- v_proj
- k_proj
- o_proj
- gate_proj
- up_proj
- down_proj

warmup_ratio: 0.05
optim: adamw_bnb_8bit
gradient_accumulation_steps: 8
learning_rate: 4.0e-5
max_grad_norm: 1.0
lr_scheduler_type: cosine_with_min_lr
lr_scheduler_kwargs:
  min_lr_rate: 0.1
num_iterations: 2
num_generations: 8
max_prompt_length: 512
max_completion_length: 12288
per_device_eval_batch_size: 4
per_device_train_batch_size: 1

# GRPO trainer config
vllm_config:
  enforce_eager: true
  gpu_memory_utilization: 0.5
  tensor_parallel_size: 2
  disable_log_stats: true
  sampling_params_dict:
    temperature: 0.6
    top_p: 0.95
    repetition_penalty: 1.05
    min_p: 0.05

bf16: true
num_train_epochs: 2

do_eval: true

save_strategy: steps
save_steps: 5
save_total_limit: 1

log_level: error
logging_strategy: steps
logging_steps: 1

eval_strategy: "no"

max_steps: -1

push_to_hub: false
hub_model_id: DeepSeek-R1-Distill-Qwen-7B
hub_strategy: every_save

report_to:
- wandb
wandb_entity: andy279
wandb_project: aimo

ignore_data_skip: true
seed: 42